git:
  filters:
    - filter_type: dynamic
      file_format: PO
      source_language: en
      source_files_expression: source/<file>.pot
      translation_files_expression: 'translations/<file>_<lang>.po'
